### ISSUE TITLE
UnboundLocalError: local variable 'original_out_dir' referenced before assignment

### ISSUE THREAD

**Issue by ColinDuquesnoy** [HackEdit/hackedit-cobol#21]
_From @brazitec on February 7, 2016 17:44_

Compilation finished with errors
15:42:37:248::ERROR::1448::hackedit_cobol.lib.build_thread::exception while running build
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\hackedit_cobol\lib\build_thread.py", line 36, in run
    self.build()
  File "c:\python34\lib\site-packages\hackedit_cobol\plugins\project_mode.py", line 367, in build
    self.project_path)
  File "c:\python34\lib\site-packages\hackedit_cobol\lib\build_thread.py", line 70, in compile
    abs_path, executable=executable, out_dir=outdir)
  File "c:\python34\lib\site-packages\hackedit_cobol\lib\compiler.py", line 468, in compile_file
    in_path, out_dir, executable, working_dir)
  File "c:\python34\lib\site-packages\hackedit_cobol\lib\compiler.py", line 578, in _get_output_path
    if system.WINDOWS and original_out_dir.endswith('/'):
UnboundLocalError: local variable 'original_out_dir' referenced before assignment
15:42:37:285::WARNING::1448::hackedit.app.events::Build finished
Compilation finished with errors

## System information

- Operating System: Windows-10-10.0.10586
- HackEdit: 1.0a2.dev15
- Python: 3.4.4 (64bits)
- Qt: 5.5.1
- PyQt: 5.5.1

_Copied from original issue: HackEdit/hackedit#72_

**Comment by ColinDuquesnoy** [comment]
_From @brazitec on February 8, 2016 1:36_

i removed all the software and reinstalled. it worked until  i add the directory structure

![screenshot 11](https://cloud.githubusercontent.com/assets/6499340/12877039/6a879f20-cdf3-11e5-857b-2a22a5a658dc.png)

**Comment by ColinDuquesnoy** [comment]
Fixed by commit HackEdit/hackedit-cobol@070b7607ce78deff70808266ca3c932c8b747855

> it worked until i add the directory structure

Thank you very much for your testing. This was a Windows specific issue when you have source files in subdirectories when using the project mode (no problem with the file mode).
