### ISSUE TITLE
Failed to open file: D:\tests\1\PRG1.c

### ISSUE THREAD

**Issue by ColinDuquesnoy** [HackEdit/hackedit-cobol#22]
_From @GitMensch on March 25, 2016 14:36_

### Description

Opened in HE before, was open last time.

### Traceback

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 90, in __init__
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1137, in parseString
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1127, in parseString
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1001, in _parseNoCache
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 2412, in parseImpl
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1005, in _parseNoCache
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 2215, in parseImpl
pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 11), (line:1, col:12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\__init__.py", line 2761, in __init__
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 94, in __init__
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'; sys.pl'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programme\entwicklung\python\lib\site-packages\hackedit\app\main_window.py", line 390, in open_file
    color_scheme=color_scheme)
  File "d:\programme\entwicklung\python\lib\site-packages\hackedit\extlibs\pyqode\core\api\utils.py", line 1096, in wrapper
    ret_val = func(*args, **kwargs)
  File "d:\programme\entwicklung\python\lib\site-packages\hackedit\extlibs\pyqode\core\widgets\splittable_tab_widget.py", line 1373, in open_document
    raise e
  File "d:\programme\entwicklung\python\lib\site-packages\hackedit\extlibs\pyqode\core\widgets\splittable_tab_widget.py", line 1367, in open_document
    tab.file.open(original_path, encoding=encoding)
  File "d:\programme\entwicklung\python\lib\site-packages\hackedit\extlibs\pyqode\core\managers\file.py", line 274, in open
    content, self.get_mimetype(path), self.encoding)
  File "d:\programme\entwicklung\python\lib\site-packages\hackedit\extlibs\pyqode\core\widgets\code_edits.py", line 152, in setPlainText
    self.syntax_highlighter.set_lexer_from_filename(self.file.path)
  File "d:\programme\entwicklung\python\lib\site-packages\hackedit\extlibs\pyqode\core\modes\pygments_sh.py", line 218, in set_lexer_from_filename
    self._lexer = get_lexer_for_filename(filename)
  File "d:\programme\entwicklung\python\lib\site-packages\hackedit\extlibs\pygments\lexers\__init__.py", line 147, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "d:\programme\entwicklung\python\lib\site-packages\hackedit\extlibs\pygments\lexers\__init__.py", line 112, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "d:\programme\entwicklung\python\lib\site-packages\hackedit\extlibs\pygments\plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\__init__.py", line 2201, in load
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\__init__.py", line 2217, in require
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\__init__.py", line 2462, in requires
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\__init__.py", line 2686, in _dep_map
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\__init__.py", line 2696, in _compute_dependencies
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\__init__.py", line 2754, in parse_requirements
  File "d:\programme\entwicklung\python\lib\site-packages\pkg_resources\__init__.py", line 2763, in __init__
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'; sys.pl'"
```

### System information

- Operating System: Windows-8-6.2.9200
- HackEdit: 1.0a2.dev60
- Python: 3.4.3 (64bits)
- Qt: 5.5.1
- PyQt: 5.5.1

### Application log

```
10:44:51:514::WARNING::14048::hackedit.app.ipc.client::server::<localhost:56797> hackedit.app.index.db:failed to executed SQL statement: "INSERT INTO Symbol_index(SYMBOL_ID, CONTENT) VALUES('579270', '78 FCODE-GET-INI-SECTION-NAMES VALUE '459'');". Error = near "459": syntax error
10:51:32:156::INFO::12024::hackedit::--------------------------------------------------------------------------------
10:51:32:156::INFO::12024::hackedit.main::starting up...
10:51:38:585::INFO::12024::hackedit.app.application::Setting up except hook...
10:51:38:590::INFO::12024::hackedit.app.application::Loading translations...
10:51:38:600::INFO::12024::hackedit.app.application::available locales: {'fr', 'default'}
10:51:38:601::INFO::12024::hackedit.app.application::Loading environemnt...
10:51:38:610::INFO::12024::hackedit.app.application::Loading shortcuts...
10:51:38:617::INFO::12024::hackedit.app.application::Creating index database...
10:51:38:623::INFO::12024::hackedit.app.application::Loading font: Hack-Bold.ttf
10:51:38:628::INFO::12024::hackedit.app.application::Loading font: Hack-BoldItalic.ttf
10:51:38:656::INFO::12024::hackedit.app.application::Loading font: Hack-Italic.ttf
10:51:38:660::INFO::12024::hackedit.app.application::Loading font: Hack-Regular.ttf
10:51:38:665::INFO::12024::hackedit.app.application::Setting up mimetypes...
10:51:38:671::INFO::12024::hackedit.app.application::Setting up user interface...
10:51:38:678::INFO::12024::hackedit.app.application::Loading plugins...
10:51:38:680::INFO::12024::hackedit.app.plugin_manager::loading template provider plugins
10:51:38:680::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: CobTemplateProvider = hackedit_cobol.plugins.templates:CobTemplatesProvider
10:51:38:811::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: PyTemplatesProvider = hackedit_python.templates:PyTemplatesProvider
10:51:38:888::INFO::12024::hackedit.app.plugin_manager::loading editor plugins
10:51:38:888::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: ImageViewer = hackedit.plugins.image_viewer:ImageViewer
10:51:38:895::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: JSONCodeEditPlugin = hackedit.plugins.editors:JSONCodeEditPlugin
10:51:39:192::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: RstCodeEditPlugin = hackedit.plugins.editors:RstCodeEditPlugin
10:51:39:192::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: CobolCodeEditPlugin = hackedit_cobol.plugins.editor:CobolCodeEditPlugin
10:51:39:923::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: PyCodeEditorPlugin = hackedit_python.editor:PyCodeEditorPlugin
10:51:40:547::INFO::12024::hackedit.app.plugin_manager::loading preferences pages plugins
10:51:40:547::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: CompilerPreferencesPlugin = hackedit_cobol.plugins.compiler_preferences:CompilerPreferencesPlugin
10:51:40:617::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: PreparserPreferencesPlugin = hackedit_cobol.plugins.preparsers_preferences:PreparserPreferencesPlugin
10:51:40:697::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: interpreters = hackedit_python.interpreters:ManageInterpreters
10:51:40:721::INFO::12024::hackedit.app.plugin_manager::loading workspace plugins
10:51:40:722::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: DocumentOutline = hackedit.plugins.outline:DocumentOutline
10:51:40:726::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: HtmlPreview = hackedit.plugins.html_preview:HtmlPreview
10:51:40:730::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: FindReplace = hackedit.plugins.find_replace:FindReplace
10:51:40:742::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: OpenDocuments = hackedit.plugins.documents:OpenDocuments
10:51:40:744::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: Terminal = hackedit.plugins.terminal:Terminal
10:51:40:756::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: CobOffsetCalculator = hackedit_cobol.plugins.offset:CobOffsetCalculator
10:51:40:793::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: CobFileManager = hackedit_cobol.plugins.file_mode:CobFileManager
10:51:40:794::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: CobFileIndicators = hackedit_cobol.plugins.indicators:CobFileIndicators
10:51:40:807::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: CobProjectManager = hackedit_cobol.plugins.project_mode:CobProjectManager
10:51:40:808::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: PyRun = hackedit_python.run:PyRun
10:51:40:810::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: PyContextMenus = hackedit_python.context_menus:PyContextMenus
10:51:40:830::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: PyCodeEditorIntegration = hackedit_python.editor:PyCodeEditorIntegration
10:51:40:831::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: PyOpenModule = hackedit_python.open_module:PyOpenModule
10:51:41:133::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: IPythonConsole = hackedit_python.ipython:IPythonConsole
10:51:41:530::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: PyRefactor = hackedit_python.refactor:PyRefactor
10:51:41:635::INFO::12024::hackedit.app.plugin_manager::  - loading plugin: CleanPycFiles = hackedit_python.clean_pyc:CleanPycFiles
10:51:41:693::INFO::12024::hackedit.app.application::Setting up templates...
10:51:41:985::INFO::12024::hackedit.app.application::Loading recent files...
10:51:41:988::INFO::12024::hackedit.app.application::Setting up welcome window...
10:51:42:027::INFO::12024::hackedit.main::running...
```

_Copied from original issue: HackEdit/hackedit#76_

**Comment by ColinDuquesnoy** [comment]
_From @GitMensch on March 25, 2016 14:44_

This only failed once, worked when reopening HE both with dev60 and dev61.
Therefore I close it, just wanted to let you know (please reopen if you see something weird).

**Comment by ColinDuquesnoy** [comment]
> pkg_resources.RequirementParseError: Invalid requirement, parse error at "'; sys.pl'"

This is the issue (not related to HE or pygments but an issue introduced in setuptools 20.2). Since that function is cached, the issue happens only once. I've patched the pygments function to catch (and ignore) this exception (temporary solution while waiting for the setuptools developers to fix this issue, there is already a bug report for this case).

**Comment by GitMensch** [comment]
Hm, why is this assigned to hackedit-cobol when the error seems a general parsing error referencing a C file?

**Comment by ColinDuquesnoy** [comment]
> Hm, why is this assigned to hackedit-cobol when the error seems a general parsing error referencing a C file?

My mistake. Thank you for your vigilance!
